var DISPATCHER_TYPES = {
    ERROR_ADD_TO_CART: 'ERROR_ADD_TO_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    ADDING_TO_CART: 'ADDING_TO_CART',
    ADDED_TO_CART: 'ADDED_TO_CART',
    ADD_TO_CART_SIZE_SELECTION_ERROR: 'ADD_TO_CART_SIZE_SELECTION_ERROR',
    
    ERROR_REMOVE_TO_CART: 'ERROR_ADD_TO_CART',
    REMOVING_FROM_CART: 'REMOVING_FROM_CART',
    REMOVED_FROM_CART: 'REMOVED_FROM_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    
    CART_ITEM_COUNT: 'CART_ITEM_COUNT',
    MINI_CART_LOADED: 'MINI_CART_LOADED',


    CONTENT_LOADED: 'CONTENT_LOADED',
    CONTENT_LOADED_ERROR: 'CONTENT_LOADED_ERROR'
};